server:
  port: 8082

spring:
  application:
    name: turbine

eureka:
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    org.springframework.cloud: 'INFO'

turbine:
  aggregator:
    clusterConfig:
  appConfig:
  instanceUrlSuffix: /hystrix.stream