server:
  port: 8083

spring:
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
    instanceId: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

encrypt:
  failOnError: true

zuul:
  routes:
    user-info-service: /user/info/**
    user-service: /user/**