server:
  port: 12306

spring:
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/

encrypt:
  failOnError: true

zuul:
  routes:
    user-service: /user/**
    user-info-service: /userinfo/**
    comment-service: /comment/**
    project-service: /project/**
    progress-service: /progress/**
    task-service: /task/**
    subtask-service: /subtask/**
    schedule-service: /schedule/**
    file-service: /file/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true