server:
  port: 8083

spring:
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

encrypt:
  failOnError: true

zuul:
  routes:
    user-info-service: /user/info/**
    user-service: /user/**
    subtask-service: /task/subtask/**
    comment-service: /comment/**
    project-service: /project/**